root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  on-premises: ./enterprise/README.md
  on-premises/quick-start: ./enterprise/quick-start/README.md
  on-premises/quick-start/setup: ./enterprise/quick-start/setup.md
  on-premises/quick-start/update: ./enterprise/quick-start/update.md
  on-premises/testing: ./enterprise/testing/README.md
  on-premises/releases: ./enterprise/releases/README.md
