version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.9
    working_directory: ~/sider/sider-docs

    steps:
      - checkout
      - run: yarn install
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run remark-cli
      - run: yarn lint
